#!/usr/bin/env bash

ln -sf ~/dotfiles/git/gitconfig ~/.gitconfig
ln -sf ~/dotfiles/git/gitignore ~/.gitignore

ln -sf ~/dotfiles/irb/aprc ~/.aprc
ln -sf ~/dotfiles/irb/irbrc ~/.irbrc
ln -sf ~/dotfiles/irb/pryrc ~/.pryrc
ln -sf ~/dotfiles/irb/unescaped_colors.rb ~/.unescaped_colors.rb
ln -sf ~/dotfiles/irb/escaped_colors.rb ~/.escaped_colors.rb

ln -sf ~/dotfiles/ruby/gemrc ~/.gemrc
ln -sf ~/dotfiles/ruby/rdebugrc ~/.rdebugrc

ln -sf ~/dotfiles/sbcl/sbclrc ~/.sbclrc

ln -sf ~/dotfiles/ctags/ctags ~/.ctags

ln -sf ~/dotfiles/emacs ~/.emacs.d

ln -sf ~/dotfiles/X11/.Xresources ~/.Xresources


sudo ln -sf ~/dotfiles/keymaps/personal.map /usr/local/share/kbd/keymaps/personal.map
sudo ln -sf ~/dotfiles/conf/vconsole.conf /etc/vconsole.conf
